name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 8 * * 1"

jobs:
  Warp_Chrome:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.10'
      - run: ls
      - name: prepare env
        run: |
          python -m pip install -r requirements.txt
          python run.py
      - name: Get current date and version
        id: date_version
        run: |
          echo "::set-output name=date::$(Get-Date -Format 'yyyy-MM-dd')"
          # 从构建输出中的 version.txt 文件提取版本信息
          echo "::set-output name=version::$(Get-Content build/release/Chrome/version.txt)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.date_version.outputs.date }}
          release_name: Chrome++ Release ${{ steps.date_version.outputs.date }}
          body: |
            Chrome++ 构建版本
            
            构建时间: ${{ steps.date_version.outputs.date }}
            版本信息: ${{ steps.date_version.outputs.version }}
            
          draft: false
          prerelease: false
      - name: Package Release
        run: |
          Compress-Archive -Path build/release/Chrome -DestinationPath build/Chrome++_${{ steps.date_version.outputs.date }}.zip
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/Chrome++_${{ steps.date_version.outputs.date }}.zip
          asset_name: Chrome++_${{ steps.date_version.outputs.date }}.zip
          asset_content_type: application/zip
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}
          path: build/release/*
          retention-days: 15
